# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' max-errors 3
zstyle :compinstall filename '/home/patrick/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

source ~/.zprofile
cd ~
PROMPT='%F{9}p%F{214}a%F{220}t%F{40}r%F{111}i%F{90}c%F{129}k%F{15}[%2~]$ '
export TERM=xterm-256color

alias ls="ls -1 --color=auto --group-directories-first --hide=lost+found"
alias steam="prime-run steam"
alias rm="trash "
alias flameshot="flameshot gui"

export PATH="/opt/cuda/bin:$PATH"
export PATH="/home/arch/patrick/.local/bin:$PATH"
